version: '3.7'
services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile-x86_64
    image: leograba/pasta-demo-credentials-setup-front:latest-x86
    depends_on:
      - back-end
    ports:
    - "8080:80"
    networks:
      - configsetup
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile-x86_64
    image: leograba/pasta-demo-credentials-setup-back:latest-x86
    networks:
      - configsetup
    ports:
      - "8000"
    volumes:
      - type: bind
        source: /greengrass/config/config.done
        target: /config.done
networks:
  configsetup: