version: '3.7'
services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: leograba/pasta-demo-credentials-setup-front:latest
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: leograba/pasta-demo-credentials-setup-back:latest
