version: '3.7'
services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile-x86_64
    image: torizonextras/pasta-demo-credentials-setup-front:latest-x86
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile-x86_64
    image: torizonextras/pasta-demo-credentials-setup-back:latest-x86
